sudo: required
dist: trusty
install:
- "curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh"
- vagga cached-make
- "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
- "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
- vagga _build test
script:
- "vagga _run cache-image cargo test"
- "vagga \
    -E UBUNTU_MIRROR=http://mirrors.us.kernel.org/ubuntu/ \
    -E ALPINE_MIRROR=http://mirrors.gigenet.com/alpinelinux/ \
     test tests --tap"
