[package]
name = "vagga"
version = "0.3.0"
authors = ["Paul Colomiets"]

[dependencies]
libc = "*"
nix = "*"
shaman = "*"
rand = "*"
argparse = "*"
quire = "*"
rustc-serialize = "*"
log = "*"
time = "*"
env_logger = "*"
url = "*"
unshare = "0.1"
signal = "0.1"

[[bin]]
name = "vagga"
path = "src/main.rs"
