[package]
name = "vagga"
version = "0.3.0"
authors = ["Paul Colomiets"]
links = "container"
build = "build.rs"

[dependencies]
libc = "*"
nix = "*"
shaman = "*"
rand = "*"
argparse = "*"
quire = "*"
rustc-serialize = "*"
log = "*"
time = "*"
env_logger = "*"
url = "*"
unshare = { git = "git://github.com/tailhook/unshare" }

[[bin]]
name = "vagga"
path = "src/main.rs"
