[package]
name = "vagga"
version = "0.3.0"
authors = ["Paul Colomiets"]
links = "container"
build = "build.rs"

[dependencies]
libc = "*"
shaman = "*"
rand = "*"
argparse = "*"
quire = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"

[[bin]]
name = "vagga"
path = "src/main.rs"
