[package]
name = "vagga"
version = "0.5.0"
authors = ["Paul Colomiets"]

[dependencies]
libc = "*"
nix = "*"
shaman = "*"
rand = "*"
argparse = "0.2.1"
rustc-serialize = "*"
log = "*"
time = "*"
env_logger = "*"
url = "*"
unshare = "0.1.11"
signal = "0.1.3"
mopa = "0.2.2"
anymap = "0.11.1"
matches = "0.1.2"
regex = "0.1.41"
scan_dir = "0.3.1"
libmount = "0.1.2"
zip = "0.1"
xz2 = "0.1.0"
tar = { git="git://github.com/alexcrichton/tar-rs", rev="c402adf"}
flate2 = "0.2.13"
bzip2 = "0.3.0"
net2 = "0.2.23"
humantime = "0.1.3"

[dependencies.quire]
git = "git://github.com/tailhook/rust-quire"
rev = "41d7e94"

[dependencies.quick-error]
git = "git://github.com/tailhook/quick-error"
branch = "context2"

[[bin]]
name = "vagga"
path = "src/main.rs"
